/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 atlas.gltf --transform
Author: Wabbaboy (https://sketchfab.com/Wabbaboy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/atlas-holding-the-earth-32002a1de62b4b3face6dd55043b6cf6
Title: Atlas holding the Earth
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Atlas(props) {
  const { nodes, materials } = useGLTF('http://RandiGustinanda.github.io/React-3D/atlas-transformed.glb')
  return (
    <group {...props} dispose={null} scale={[0.01,0.01,0.01]}>
      <group rotation={[-Math.PI / 2, 0, 0 ]}>
        <mesh geometry={nodes['Group1_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
        <mesh geometry={nodes['Group1_03-_Default_0'].geometry} material={materials['03-_Default']} />
      </group>
    </group>
  )
}

useGLTF.preload('http://RandiGustinanda.github.io/React-3DReact-3D/atlas-transformed.glb')
