/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 statue.gltf --transform
Author: Zafio (https://sketchfab.com/zafio)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/statue-of-edward-snowden-04d109f5edb3407ca8939a109742fece
Title: Statue Of Edward Snowden
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Statue(props) {
  const { nodes, materials } = useGLTF('/statue-transformed.glb')
  
  const groupRef = useRef()

  return (
    <group ref={groupRef} {...props} dispose={null} scale={[0.6, 0.6, 0.6]}>
      <group position={[0.4, 1.09, 1.09]} rotation={[3.14, 0, -3.14]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials['default']}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials['default']}
          castShadow
          receiveShadow
        />
      </group>
    </group>
  )
}

useGLTF.preload('/statue-transformed.glb')
